defmodule EctoShorts.Testing do
  @moduledoc """
  This API provides helpers to make testing easier in Ecto.

  This module provides macros to make it easier to write assertions
  when testing queries or dynamic expressions. These assertions work
  by comparing the string representations of Ecto queries, dynamic
  expressions, or the generated SQL output.

  It includes:

    * `assert_dynamic/2` – Compare two `dynamic/2` expressions by their AST.
    * `assert_query/2` – Compare two `Ecto.Query` structs by their stringified form.
    * `assert_sql/4` – Compare SQL output generated by queries.
    * `refute_*/2` versions – Inverse assertions to confirm inequality.
  """
  alias ExUnit.Assertions

  @doc """
  Asserts that two `dynamic/2` expressions are structurally identical.

  It compares both expressions by converting them to strings using
  `Macro.to_string/1`, which normalizes their AST.

  ## Examples

      assert_dynamic(
        dynamic([p], p.id == 1),
        dynamic([p], p.id == 1)
      )
  """
  def assert_dynamic(dyn_a, dyn_b) do
    left = Macro.to_string(dyn_a)
    right = Macro.to_string(dyn_b)

    if left !== right do
      Assertions.flunk("Expected dynamic expressions to be equal:\n\nleft:  #{left}\nright: #{right}")
    end

    :ok
  end

  @doc """
  Refutes that two `dynamic/2` expressions are structurally identical.

  Uses `Macro.to_string/1` for comparison.

  ## Examples

      refute_dynamic(
        dynamic([p], p.id == 1),
        dynamic([p], p.id == 2)
      )
  """
  def refute_dynamic(dyn_a, dyn_b) do
    left = Macro.to_string(dyn_a)
    right = Macro.to_string(dyn_b)

    if left === right do
      Assertions.flunk("Expected dynamic expressions to be different, but both were:\n\n#{left}")
    end

    :ok
  end

  @doc """
  Asserts that two queries generate identical SQL using the given adapter and repo.

  This checks the actual SQL produced by Ecto using `Ecto.Adapters.SQL.to_sql/3`.

  ## Parameters

    * `repo` – The Ecto repo module.
    * `query_a`, `query_b` – The queries to compare.
    * `kind` – The kind of SQL to generate. Defaults to `:all`.

  ## Examples

      assert_sql(Ecto.Adapters.Postgres, Repo, query1, query2)
  """
  def assert_sql(repo, query_a, query_b, kind \\ :all) do
    left = Ecto.Adapters.SQL.to_sql(kind, repo, query_a)
    right = Ecto.Adapters.SQL.to_sql(kind, repo, query_b)

    if left !== right do
      Assertions.flunk(
        "Expected queries to produce the same SQL:\n\nleft:  #{inspect(left)}\nright: #{inspect(right)}"
      )
    end

    :ok
  end

  @doc """
  Refutes that two queries generate identical SQL using the given repo.

  Useful when asserting that two queries should *not* compile to the same SQL.

  ## Examples

      refute_sql(Repo, query1, query2)
  """
  def refute_sql(repo, query_a, query_b, kind \\ :all) do
    left = Ecto.Adapters.SQL.to_sql(kind, repo, query_a)
    right = Ecto.Adapters.SQL.to_sql(kind, repo, query_b)

    if left === right do
      Assertions.flunk("Expected queries to produce different SQL, but both were:\n\n#{inspect(left)}")
    end

    :ok
  end

  @doc """
  Asserts that two `Ecto.Query` structs are equal by comparing their string representation.

  Uses the `Ecto.Query` inspect protocol to convert the queries to strings.

  ## Examples

      assert_query(
        from(p in Post, where: p.id === 1),
        from(p in Post, where: p.id === 1)
      )
  """
  def assert_query(query_a, query_b) do
    left = inspect(query_a)
    right = inspect(query_b)

    if left !== right do
      Assertions.flunk("Expected queries to be equal:\n\nleft:  #{left}\nright: #{right}")
    end

    :ok
  end

  @doc """
  Refutes that two `Ecto.Query` structs are equal.

  Uses the `Ecto.Query` inspect protocol to convert the queries to strings.

  ## Examples

      refute_query(
        from(p in Post, where: p.id === 1),
        from(p in Post, where: p.id === 2)
      )
  """
  def refute_query(query_a, query_b) do
    left = inspect(query_a)
    right = inspect(query_b)

    if left === right do
      Assertions.flunk("Expected queries to be different, but both were:\n\n#{left}")
    end

    :ok
  end

  defmacro __using__(opts) do
    quote do
      opts = unquote(opts)

      alias EctoShorts.Testing

      @repo Keyword.get(opts, :repo, EctoShorts.Config.repo())

      def assert_dynamic(dyn_a, dyn_b) do
        Testing.assert_dynamic(dyn_a, dyn_b)
      end

      def refute_dynamic(dyn_a, dyn_b) do
        Testing.refute_dynamic(dyn_a, dyn_b)
      end

      def assert_sql(query_a, query_b, kind \\ :all) do
        Testing.assert_sql(@repo, query_a, query_b, kind)
      end

      def refute_sql(query_a, query_b, kind \\ :all) do
        Testing.refute_sql(@repo, query_a, query_b, kind)
      end

      def assert_query(query_a, query_b) do
        Testing.assert_query(query_a, query_b)
      end

      def refute_query(query_a, query_b) do
        Testing.refute_query(query_a, query_b)
      end
    end
  end
end
