defmodule EctoShorts.Testing do
  @doc """
  Asserts that two dynamic expressions are identical.
  """
  defmacro assert_dynamic(dyn_a, dyn_b) do
    quote do
      assert Macro.to_string(unquote(dyn_a)) === Macro.to_string(unquote(dyn_b))
    end
  end

  defmacro refute_dynamic(dyn_a, dyn_b) do
    quote do
      refute Macro.to_string(unquote(dyn_a)) === Macro.to_string(unquote(dyn_b))
    end
  end

  @doc """
  Asserts the SQL generated by both queries are identical.
  """
  defmacro assert_sql(repo, query_a, query_b) do
    quote do
      assert Ecto.Adapters.SQL.to_sql(:all, unquote(repo), unquote(query_a)) ===
               Ecto.Adapters.SQL.to_sql(:all, unquote(repo), unquote(query_b))
    end
  end

  defmacro refute_sql(repo, query_a, query_b) do
    quote do
      refute Ecto.Adapters.SQL.to_sql(:all, unquote(repo), unquote(query_a)) ===
               Ecto.Adapters.SQL.to_sql(:all, unquote(repo), unquote(query_b))
    end
  end

  @doc """
  Asserts both Ecto query expressions are identical.
  """
  defmacro assert_query(query_a, query_b) do
    quote do
      assert inspect(unquote(query_a), pretty: true) === inspect(unquote(query_b), pretty: true)
    end
  end

  defmacro refute_query(query_a, query_b) do
    quote do
      refute inspect(unquote(query_a), pretty: true) === inspect(unquote(query_b), pretty: true)
    end
  end
end
