defmodule EctoShorts.Testing do
  @moduledoc since: "3.0.0"
  @moduledoc """
  Assertion helpers for testing Ecto queries and dynamic expressions.

  Use this module in your test files to make assertions about query
  structure and SQL output without relying on brittle string matching.

  ## Getting started

  Add `use EctoShorts.Testing` to your test module to get repo-bound
  helpers that delegate to this module:

      defmodule MyApp.QueryTest do
        use ExUnit.Case
        use EctoShorts.Testing, repo: MyApp.Repo

        test "filters by title" do
          q1 = from p in Post, where: p.title == ^"Hello"
          q2 = EctoShorts.CommonFilters.convert_params_to_filter(Post, %{title: "Hello"})
          assert_query(q1, q2)
        end
      end

  ## Available assertions

  * `assert_dynamic/2` - compare two `dynamic/2` expressions by their AST string.
  * `refute_dynamic/2` - assert two dynamic expressions are different.
  * `assert_query/2` - compare two `Ecto.Query` structs by their inspect form.
  * `refute_query/2` - assert two queries produce different inspect output.
  * `assert_sql/3-4` - compare the SQL generated by two queries.
  * `refute_sql/3-4` - assert two queries produce different SQL.

  When using `use EctoShorts.Testing`, the `:repo` option is bound at
  compile time, so `assert_sql/2-3` and `refute_sql/2-3` do not require
  an explicit repo argument.

  See also `EctoShorts.CommonFilters`, `EctoShorts.Dynamics`, and
  `EctoShorts.Actions`.
  """
  alias ExUnit.Assertions

  @doc """
  Asserts that two `dynamic/2` expressions are structurally identical.

  Compares both expressions by converting them to strings via
  `Macro.to_string/1`, which normalizes the AST. Calls `ExUnit.Assertions.flunk/1`
  with a diff when the expressions differ.

  Returns `:ok` on success.

  ## Examples

      iex> import Ecto.Query
      ...> EctoShorts.Testing.assert_dynamic(
      ...>   dynamic([p], p.id == 1),
      ...>   dynamic([p], p.id == 1)
      ...> )
      :ok

  See also `refute_dynamic/2` and `assert_query/2`.
  """
  def assert_dynamic(dyn_a, dyn_b) do
    left = Macro.to_string(dyn_a)
    right = Macro.to_string(dyn_b)

    if left !== right do
      Assertions.flunk("Expected dynamic expressions to be equal:\n\nleft:  #{left}\nright: #{right}")
    end

    :ok
  end

  @doc """
  Refutes that two `dynamic/2` expressions are structurally identical.

  Calls `ExUnit.Assertions.flunk/1` when the expressions produce the same
  `Macro.to_string/1` output. Returns `:ok` when they differ.

  ## Examples

      iex> import Ecto.Query
      ...> EctoShorts.Testing.refute_dynamic(
      ...>   dynamic([p], p.id == 1),
      ...>   dynamic([p], p.id == 2)
      ...> )
      :ok

  See also `assert_dynamic/2`.
  """
  def refute_dynamic(dyn_a, dyn_b) do
    left = Macro.to_string(dyn_a)
    right = Macro.to_string(dyn_b)

    if left === right do
      Assertions.flunk("Expected dynamic expressions to be different, but both were:\n\n#{left}")
    end

    :ok
  end

  @doc """
  Asserts that two queries generate identical SQL using the given repo.

  Uses `Ecto.Adapters.SQL.to_sql/3` to compile each query and compares
  the resulting `{sql_string, params}` tuples.

  `kind` is the SQL operation type (`:all`, `:update_all`, `:delete_all`);
  defaults to `:all`.

  ## Examples

      iex> import Ecto.Query
      ...> q1 = from p in EctoShorts.Schema.Post, where: p.id == ^1
      ...> q2 = EctoShorts.CommonFilters.convert_params_to_filter(EctoShorts.Schema.Post, %{id: 1})
      ...> EctoShorts.Testing.assert_sql(EctoShorts.Repo, q1, q2)
      :ok

  See also `refute_sql/4` and `assert_query/2`.
  """
  def assert_sql(repo, query_a, query_b, kind \\ :all) do
    left = Ecto.Adapters.SQL.to_sql(kind, repo, query_a)
    right = Ecto.Adapters.SQL.to_sql(kind, repo, query_b)

    if left !== right do
      Assertions.flunk(
        "Expected queries to produce the same SQL:\n\nleft:  #{inspect(left)}\nright: #{inspect(right)}"
      )
    end

    :ok
  end

  @doc """
  Refutes that two queries generate identical SQL using the given repo.

  Calls `ExUnit.Assertions.flunk/1` when the SQL output of both queries
  matches. Returns `:ok` when they differ.

  ## Examples

      iex> import Ecto.Query
      ...> q1 = from p in EctoShorts.Schema.Post, where: p.id == ^1
      ...> q2 = from p in EctoShorts.Schema.Post, where: p.id == ^2
      ...> EctoShorts.Testing.refute_sql(EctoShorts.Repo, q1, q2)
      :ok

  See also `assert_sql/4`.
  """
  def refute_sql(repo, query_a, query_b, kind \\ :all) do
    left = Ecto.Adapters.SQL.to_sql(kind, repo, query_a)
    right = Ecto.Adapters.SQL.to_sql(kind, repo, query_b)

    if left === right do
      Assertions.flunk("Expected queries to produce different SQL, but both were:\n\n#{inspect(left)}")
    end

    :ok
  end

  @doc """
  Asserts that two `Ecto.Query` structs are equal by comparing their inspect output.

  Uses the `Ecto.Query` inspect protocol to normalize both queries to strings.
  Calls `ExUnit.Assertions.flunk/1` with a diff when they differ.

  ## Examples

      iex> import Ecto.Query
      ...> EctoShorts.Testing.assert_query(
      ...>   from(p in EctoShorts.Schema.Post, where: p.id == ^1),
      ...>   from(p in EctoShorts.Schema.Post, where: p.id == ^1)
      ...> )
      :ok

  See also `refute_query/2` and `assert_sql/4`.
  """
  def assert_query(query_a, query_b) do
    left = inspect(query_a)
    right = inspect(query_b)

    if left !== right do
      Assertions.flunk("Expected queries to be equal:\n\nleft:  #{left}\nright: #{right}")
    end

    :ok
  end

  @doc """
  Refutes that two `Ecto.Query` structs are equal.

  Calls `ExUnit.Assertions.flunk/1` when both queries produce the same
  inspect output. Returns `:ok` when they differ.

  ## Examples

      iex> import Ecto.Query
      ...> EctoShorts.Testing.refute_query(
      ...>   from(p in EctoShorts.Schema.Post, where: p.id == ^1),
      ...>   from(p in EctoShorts.Schema.Post, where: p.id == ^2)
      ...> )
      :ok

  See also `assert_query/2`.
  """
  def refute_query(query_a, query_b) do
    left = inspect(query_a)
    right = inspect(query_b)

    if left === right do
      Assertions.flunk("Expected queries to be different, but both were:\n\n#{left}")
    end

    :ok
  end

  @doc false
  defmacro __using__(opts) do
    quote do
      opts = unquote(opts)

      alias EctoShorts.Testing

      @repo Keyword.get(opts, :repo, EctoShorts.Config.repo())

      def assert_dynamic(dyn_a, dyn_b) do
        Testing.assert_dynamic(dyn_a, dyn_b)
      end

      def refute_dynamic(dyn_a, dyn_b) do
        Testing.refute_dynamic(dyn_a, dyn_b)
      end

      def assert_sql(query_a, query_b, kind \\ :all) do
        Testing.assert_sql(@repo, query_a, query_b, kind)
      end

      def refute_sql(query_a, query_b, kind \\ :all) do
        Testing.refute_sql(@repo, query_a, query_b, kind)
      end

      def assert_query(query_a, query_b) do
        Testing.assert_query(query_a, query_b)
      end

      def refute_query(query_a, query_b) do
        Testing.refute_query(query_a, query_b)
      end
    end
  end
end
